services:
  app:
    build:
      context: .
    image: devops-nodejs-cicd-lab:local
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      APP_VERSION: local
    restart: unless-stopped
